I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/outside.rpy", line 116, in script
    if dumpsterItem in roomItems["dumpster"]:
  File "game/outside.rpy", line 116, in <module>
    if dumpsterItem in roomItems["dumpster"]:
NameError: name 'dumpsterItem' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/outside.rpy", line 116, in script
    if dumpsterItem in roomItems["dumpster"]:
  File "/Users/jamespattison/Desktop/renpy-8.0.0-sdk/renpy/ast.py", line 2095, in execute
    if renpy.python.py_eval(condition):
  File "/Users/jamespattison/Desktop/renpy-8.0.0-sdk/renpy/python.py", line 1080, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/jamespattison/Desktop/renpy-8.0.0-sdk/renpy/python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/outside.rpy", line 116, in <module>
    if dumpsterItem in roomItems["dumpster"]:
NameError: name 'dumpsterItem' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.0.22062402
Fattay Chronicles 1.0
Fri Jul  1 13:08:20 2022
